Algoritmo "soma"
// 
// Problema "soma"
//Fazer um programa para ler dois valores inteiros X e Y,
//e depois mostrar na tela o valor da soma destesnúmeros
//
Var
// Seção de Declarações das variáveis
   soma, n1, n2: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("digite uma numero:")
    leia(n1)
    escreva("digite outro numero:")
    leia(n2)
    
    soma <- n1 + n2
    escreva("A soma de ", n1," + ", n2," é:",soma )


Fimalgoritmo